Personal:
  $FIRST$: Nalin
  $LAST$: Jha
  $TITLE$: Senior at North Cross School
  $BIO$: I am a high school senior interested in Computer Science, Mathematics, Chess, and Robotics. I also enjoy playing soccer and tennis.
  $LINKEDIN$: https://www.linkedin.com/in/nalin-j-47371510a/
  $EMAIL$: njha714@gmail.com
Projects:
  - $TITLE$: Coding Club
    $URL$: "https://willishallherald.wordpress.com/2018/04/12/coding-competes-uva/"
    $ICON$: terminal
    $BLURB$: I founded the Coding Club at my high school. The team I recruited and captained placed 2nd in the Advanced Division of Code Quest in 2018 (Suffolk, VA location).
  - $TITLE$: Chess 
    $URL$: http://www.uschess.org/msa/MbrDtlMain.php?16028844
    $ICON$: trophy
    $BLURB$: "I am proud member of the Roanoke Chess club and enjoy working with our local National Master Mr. Russell Potter. I have won the following tournaments: 2016 Maggie L. Walker Summer Scholastic, 2016 Star City Challenge 2017 VA Commonwealth Games, 2017 Virginia Closed Amateur State Championship"
  - $TITLE$: Educational YouTube Channel
    $URL$: https://www.youtube.com/channel/UCjhlL4txLUhArG0aVXY38Qg
    $ICON$: youtube-play
    $BLURB$: "I make YouTube videos covering some of the concepts that I thought would be useful for my fellow high schoolers."
  - $TITLE$: Robotics Club
    $URL$: https://www.youtube.com/watch?v=Ny3k8LFInko&feature=youtu.be
    $ICON$: youtube-play
    $BLURB$: "I am the lead programmer of my school's robotics team. I use the Java programming language to integrate sensor data with robotic motion."
  - $TITLE$: Varsity Soccer
    $URL$: https://youtu.be/4FGkuLeSXlU?t=3972
    $ICON$: youtube-play
    $BLURB$: "I have played on my school's varisty soccer team since 9th grade. In my senior year, I started in the state championship game and helped my team win the title. The video shows the walkout of the players in the starting lineup. I am #8.
