Personal:
  $FIRST$: Nalin
  $LAST$: Jha
  $TITLE$: Senior at North Cross School
  $BIO$: I am a high school senior interested in Computer Science, Mathematics, Robotics, and Chess. I also enjoy playing soccer and tennis.
  $LINKEDIN$: https://willishallherald.wordpress.com/2018/01/29/academic-stars-shine-nalin-jha/
  $EMAIL$: njha714@gmail.com
Projects:
  - $TITLE$: Coding Club
    $URL$: https://willishallherald.wordpress.com/2018/04/12/coding-competes-uva/
    $ICON$: code
    $BLURB$: I founded the Coding Club at my high school. The team I recruited and captained placed 2nd in the Advanced Division of Code Quest in 2018 (Suffolk, VA location).
  - $TITLE$: Chess
    $URL$: http://www.roanokechess.com/2017_Virginia_State_Championship.php
    $ICON$: trophy
    $BLURB$: I am proud member of the Roanoke Chess club and enjoy working with our local National Master Mr. Russell Potter. At my peak, I was ranked in the top 3% of all players under the age of 21 in the United States. In 2017, I was the Virginia State Amateur Champion, and I have placed 1st in 5 of my 14 tournaments.
  - $TITLE$: Educational YouTube Channel
    $URL$: https://www.youtube.com/channel/UCjhlL4txLUhArG0aVXY38Qg
    $ICON$: youtube-play
    $BLURB$: I make YouTube videos covering some of the concepts that I thought would be useful for my fellow high schoolers.
  - $TITLE$: Robotics Club
    $URL$: https://www.youtube.com/watch?v=Ny3k8LFInko&feature=youtu.be
    $ICON$: android
    $BLURB$: I am the lead programmer of my school's robotics team. I use the Java programming language to integrate sensor data with robotic motion. In 2018, my team placed 5th overall and was seeded 4th in the semifinals playoffs. In 2019, we placed 4th overall and managed to secure a 3rd place seeding in the playoffs.
  - $TITLE$: Hour of Code
    $URL$: https://www.instagram.com/p/BqufhPJF0w7/
    $ICON$: code
    $BLURB$: My school chooses one week during the winter to celebrate Computer Science Education Week. This year, I was introduced by the faculty as the local computer expert. I had the opportunity to be on stage during school assembly and guide the headmaster through his first hour of coding.
  - $TITLE$: Varsity Soccer State Championship
    $URL$: https://www.instagram.com/p/BqAS_Q0F7yD/
    $ICON$: trophy
    $BLURB$: I have played on my school's varisty soccer team since 9th grade. In my senior year, I was in the starting lineup for the state championship game and helped my team win the title.
  - $TITLE$: Varsity Tennis
    $URL$: http://www.maxpreps.com/athlete/nalin-jha/3nQc9U_mEeS00gAmVebEWg/gendersport/tennis-stats.htm
    $ICON$: trophy
    $BLURB$: I enjoy playing tennis at the varsity level. I have participated in two state championship teams, and my career record is 20 wins and 8 losses. This year, I have been selected as the team captain.
  - $TITLE$: Capstone Project
    $URL$: https://docs.google.com/document/d/1_eoWfOwBP9eP9r-4tTNMuxx80qCdulLHZNahFZE0ZAM/edit?usp=sharing
    $ICON$: code
    $BLURB$: This project involves the implementation of an artificial neural network that will learn to recognize handwritten digits. The artificial neural network implemented in this project will be expected to identify 10,000 handwritten digits at a 95% or greater success rate.
